---
# Icons Class Select : | bx bxl-dribbble | bx bx-file | bx bx-tachometer | bx bx-layer

- name: "Cloud Ops"
  icon: "bx bxl-dribbble"
  description: "Cloud Strategy | Consultation | Migration | Automation | Cost Optimisation"
