---
#https://iconify.design/icon-sets/bx/
- name: "Cloud Ops"
  icon: "bx bx-cloud"
  description: "Cloud Strategy | Consultation | Migration | Automation | Cost Optimisation"
- name: "DevOps"
  icon: "bx bx-code-block"
  description: "Infra Automation | Performance Optimisation | Continuous Integration  & Deployment | Configuration Management | Monitoring & Alerting | DR Strategy |"
- name: "Data & Analytics"
  icon: "bx bx-coin-stack"
  description: "Data Analysis | Data Visualisation | Data Migration | Data DevOps | Reporting |"
- name: "Security"
  icon: "bx bx-check-shield"
  description: "DevSecOps | Security Assessment | Cloud Security | IT Infra Security | Risk Management | ITSM | IT Auditing |"
- name: "Digital Marketing"
  icon: "bx bx-code-alt"
  description: "Content Marketing | Social Marketing | SEO Optimisation | Web Development |App Development |"
- name: "SRE & NOC"
  icon: "bx bxs-support"
  description: "24 x 7 Support Application / Infrastructure Support | Proactive monitoring & remediation | "
- name: "Trainings"
  icon: "bx bx-edit"
  description: "Instructor-led Training | Virtual Classroom Training | Corporate Trainings "

